# Generated by Django 4.0.6 on 2022-12-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField(blank=True, null=True)),
                ('short_decsription', models.CharField(max_length=100)),
                ('long_decsription', models.TextField(default='DESC')),
                ('most_popular', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('date1', models.DateField(blank=True, null=True)),
                ('short_decsription', models.CharField(max_length=100)),
                ('long_decsription', models.TextField(default='DESC')),
                ('most_popular', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
            ],
        ),
    ]
