# Generated by Django 4.0.6 on 2022-12-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='cate',
            field=models.SlugField(choices=[('ثقافة', 'ثقافة')], default=4),
            preserve_default=False,
        ),
    ]
