# Generated by Django 4.0.6 on 2022-12-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='main2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new',
            name='main2',
            field=models.BooleanField(default=False),
        ),
    ]
