# Generated by Django 4.1.4 on 2022-12-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_main_blog_main2_new_main_new_main2'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='type',
            field=models.CharField(choices=[('News', 'News'), ('Blogs', 'Blogs')], default='Blogs', max_length=50),
        ),
    ]
