# Generated by Django 4.1.4 on 2022-12-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('date_time', models.DateTimeField(default=True)),
                ('short_description', models.CharField(max_length=100)),
                ('long_description', models.TextField()),
                ('most_popular', models.BooleanField(default=False)),
            ],
        ),
    ]
