# Generated by Django 4.0.6 on 2022-12-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_new_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='cate',
            field=models.CharField(choices=[('ثقافة', 'ثقافة')], max_length=12),
        ),
    ]
