# Generated by Django 4.1.4 on 2022-12-25 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_new_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
