# Generated by Django 4.1.4 on 2022-12-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
