# Generated by Django 4.1.4 on 2022-12-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blog_date_time_alter_news_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date_time',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=True),
        ),
    ]
