# Generated by Django 4.1.4 on 2022-12-21 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_blog_date_alter_news_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date',
            new_name='date_created',
        ),
    ]
