# Generated by Django 4.1.4 on 2022-12-21 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_date_blog_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date_created',
        ),
    ]
