# Generated by Django 4.1.4 on 2022-12-21 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_blog_date_created_remove_news_date_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
