# Generated by Django 4.1.4 on 2022-12-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_blog_date_time_alter_news_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField(auto_now=True)),
                ('short_decsription', models.CharField(max_length=100)),
                ('long_decsription', models.TextField(default='DESC')),
                ('most_popular', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='short_description',
            new_name='short_decsription',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='long_description',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='long_decsription',
            field=models.TextField(default='DESC'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
