# Generated by Django 4.1.4 on 2022-12-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_new_delete_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
