# Generated by Django 4.1.4 on 2022-12-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_blog_date_alter_new_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
