# Generated by Django 4.1.4 on 2022-12-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_blog_date_alter_new_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
